### ISSUE TITLE
Fix placeholder text for password re-entry

### ISSUE THREAD

**Issue by GinaAbrams** [leather-io/extension#1012]
Screenshot attached, the set password vs. enter password you've already set language is a bit confusing. 
<img width="419" alt="Screen Shot 2021-02-20 at 6 03 01 PM" src="https://user-images.githubusercontent.com/30627583/108610742-045e8200-73a6-11eb-825c-c9ba2918503f.png">

**Comment by markmhendrickson** [comment]
~~Is this confusing because the user isn't clear as to whether they're entering a new vs. existing password? Or for other reasons?~~

I see now that the placeholder says "Set a password", which is indeed confusing since it suggests setting a _new_ password. However, this form is form is meant for entering an _existing_ one.

I'd recommend "Enter your password" or something equivalent instead.

**Comment by aulneau** [comment]
will be resolved with https://github.com/blockstack/ux/pull/1036

**Comment by timstackblock** [comment]
Looks good
