### ISSUE TITLE
CORS error using Firefox extension

### ISSUE THREAD

**Issue by friedger** [leather-io/extension#1106]
When logging in (to speed spend) I saw a CORS error:
```
"Unable to fetch account data from https://stacks-node-api.testnet.stacks.co" due to CORS

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://stacks-node-api.testnet.stacks.co/extended/v1/tx/mempool?limit=30. (Reason: header ‘x-hiro-product’ is not allowed according to header ‘Access-Control-Allow-Headers’ from CORS preflight response).
```
After adding `x-hiro-product`, I could login with chrome extension, however, I still received the error with the firefox extension.

After disabling the CORS settings on the server, the error was gone.

The Firefox extension should work with CORS settings enabled.

**Comment by CharlieC3** [comment]
CORS was temporarily enabled on the testnet API as a result of [this issue](https://github.com/blockstack/stacks-blockchain-api/issues/540). However, it seems the root cause of the referenced issue was performance-related and not because CORS was necessarily needed. So if we can leave CORS disabled (like it's always been), we might not need to solve for anything here.
