### ISSUE TITLE
Add password strength indicator

### ISSUE THREAD

**Issue by whoabuddy** [leather-io/extension#1205]
Related to #1204, it would be great if the password requirements were displayed on the initial screen, and an indicator was shown that the password meets the expected criteria, e.g.: 

![jQuery-Plugin-For-Password-Strength-Checker-and-Indicator-Password-Strength](https://user-images.githubusercontent.com/9038904/119136484-50e94600-ba05-11eb-9770-917d23085374.jpg)

Also, the Done button should remain grayed out until the requirements are met, so the user doesn't think they can submit an invalid password.

**Comment by andresgalante** [comment]
I agree, the password UX is less than ideal.

There is a design issue related to this https://github.com/blockstack/stacks-wallet-web/issues/1008. We'll get to work on it as part of improving the extension's overall UX experience.

**Comment by kyranjamie** [comment]
As with the desktop wallet, the extension uses [`zxcvbn`](https://github.com/dropbox/zxcvbn), which uses an algorithm rather than an exact set requirements.

Read more about zxcvbn here https://nakedsecurity.sophos.com/2016/08/17/why-you-still-cant-trust-password-strength-meters/

I'd suggest we focus on providing better guidance on what a good password is, rather than trying to target specific set of requirements.

Edit: @jasperjansz I'd consider adding some kind of "extension may seem unresponsive" when the password's being submit/wallet opening. Argon2 hammers the CPU and it takes ages. Some more feedback, beyond the spinner, would be reassuring nothing's broken.

**Comment by markmhendrickson** [comment]
I'm adding this to [the "Improve onboarding" milestone](https://github.com/blockstack/stacks-wallet-web/milestone/41) so @jasperjansz can consider it while he looks at that work in general.

**Comment by andresgalante** [comment]
Jasper has a design for this proposal ![unknown-1](https://user-images.githubusercontent.com/1832037/122575937-95c5c400-d027-11eb-9937-6442ec7b2d96.png)
