### ISSUE TITLE
Users can replace-by-fee their own transactions by accident

### ISSUE THREAD

**Issue by MarvinJanssen** [leather-io/extension#1270]
It is possible to replace-by-fee your own transactions by queuing transactions in quick succession. This happened for people on btc.us when they clicked Preorder and then Register within seconds of each other. I have debated adding a timer or waiting until the Preorder transaction is seen on the network but I think this should be fixed on the extension level.

**Comment by markmhendrickson** [comment]
We discussed this as a team during our weekly meeting yesterday and the core issue here seems to be related to these two transactions sharing the same nonce. And apparently this nonce problem has been rather unique to the BTC app in how transactions have been generated? 

If that's indeed the case, we should figure out how to iron out the nonce issue instead of implementing some other mechanism to avoid accidental replace-by-fees (e.g. a timer).

@aulneau may have additional thoughts here to share.

**Comment by MarvinJanssen** [comment]
Agreed. If anything, the BTC app is just the first app that brought the issue to light. Nothing special goes on when generating those transactions. 

https://github.com/hirosystems/btc-us-website/blob/a99e59f0da83dee645534b3b664aeaebdd53af80/src/lib/nameservice.js#L93-L123

**Comment by aulneau** [comment]
This is not necessarily a bug in the web extension, nor is this a bug in the BTC app. Moreso, this is a result of higher network activity and nodes/api endpoints being out of sync. During the height of the increased activity due to the interest in registering names via the .btc app, there was a slow down in the network and it was harder for the API to always present the latest data. Given that, it's nearly impossible for any client to correctly determine the next nonce for a given user. It's possible we can do a better job of keeping a local client side state of where the users nonce is at, but I think this is something that would ultimately be improved via work on the API and tooling around the network. 

There is a new endpoint on the API that will be released once the microblock support work is completed that will enable clients to better know the correct nonce to use, and there might be a service in the future that acts as a broadcaster which will orestrate all of this behavior so clients don't need to implement this complex logic.

**Comment by MarvinJanssen** [comment]
Interestingly, this still happened just a few days ago with someone at the Foundation. (So when network activity was lower than on the launch day of btc.us.)

**Comment by aulneau** [comment]
> Interestingly, this still happened just a few days ago with someone at the Foundation. (So when network activity was lower than on the launch day of btc.us.)

**Comment by aulneau** [comment]
Yeah there are some improvements we are about to ship to nonce calculation in the extension, and like I said, when the API changes are live, that will vastly improve the nonce usage in all of our wallets/clients.
