### ISSUE TITLE
Add guidance about memos to send and receive modals

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#1311]
We should add the same enhancements around memo guidance as provided in the desktop wallet with https://github.com/blockstack/stacks-wallet/issues/571

**Comment by jasperjansz** [comment]
@markmhx I'm thinking as part of this memo issue we can add the guidance to the confirmation screen and otherwise leave it as is (option A). We can then make further improvements to the confirmation screen and preceding flow (option B) as part of another issue. Do you agree?

![image](https://user-images.githubusercontent.com/25477905/129556825-e6d8cddf-63dd-4604-b1a6-96311d9330be.png)

**Comment by markmhendrickson** [comment]
Yep looks good to me. Do we want a modification to the receive modal as well, to clarify that a memo is not needed even if the exchange etc. used for sending says it is?

**Comment by jasperjansz** [comment]
Ok moving to backlog.

Receive, add the message: https://www.figma.com/file/VupGh90FJtT0dcBj2Sh7bb/%F0%9F%93%8FSpec?node-id=3%3A10
For send, we'll just add the reminder on the confirmation screen for now, and keep the current layout: https://www.figma.com/file/VupGh90FJtT0dcBj2Sh7bb/%F0%9F%93%8FSpec?node-id=195%3A3147
