### ISSUE TITLE
Enhancement:Web wallet popup dialogue to be moveable

### ISSUE THREAD

**Issue by Eshwari007** [leather-io/extension#1337]
User notices that at times pop up wallet is static and cant 

https://user-images.githubusercontent.com/38872890/123009475-bde85680-d38a-11eb-9354-fccc1e4846db.mov

be moved to location where user would prefer,
Attaching the video recording for perusal.

**Comment by markmhendrickson** [comment]
I'm not sure if I've seen an extension popup moveable like this before? Is it possible technically?

**Comment by kyranjamie** [comment]
No, it isn't.

There are two "popups" that show a very similar UI
1) The popup that appears when clicking the Stacks Wallet icon (not movable)
2) The new window extension popup that shows when you try to sign a transaction (movable)

No. 1 cannot be moved as it isn't an OS-level window (no toolbar, coloured buttons etc)

Closing out as this is expected behaviour
