### ISSUE TITLE
Add "next steps" to home

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#1478]
https://www.figma.com/file/VupGh90FJtT0dcBj2Sh7bb/📏Spec?node-id=62%3A5898

- [x] #1500
- [x] Implement the close button. 
- [x] Link steps to pages or external URL's
- [x] Check off steps when the step has been completed or the URL has been visited
- [x] Implement the grid view for inside the popup

Links:
- Fund: fund page
- Name: tbd (external URL)
- Back up: Secret Key page
- Explore: stacks.co/apps

![image](https://user-images.githubusercontent.com/28991/136795833-2b33fa04-a708-497e-8822-b1ab91ea87e0.png)

**Comment by TarekDTM** [comment]
would love to help with this issue

**Comment by andresgalante** [comment]
Hi @TarekDTM that'd be amazing. What do you have in mind?

**Comment by markmhendrickson** [comment]
@eugeniadigon It looks like we may be missing two illustrations here for "Register a name" and "Explore apps"?

**Comment by ginny-d** [comment]
> @eugeniadigon It looks like we may be missing two illustrations here for "Register a name" and "Explore apps"?

Yes, will try to tackle those this week

**Comment by ginny-d** [comment]
The updated designs for this screen can be found here: https://www.figma.com/file/VupGh90FJtT0dcBj2Sh7bb/%F0%9F%93%8FSpec?node-id=1842%3A12437

**Comment by fbwoolf** [comment]
Alright @fbwoolf, we've settled with option A (short and sweet 🍬 )

Here's the [Figma prototype](https://www.figma.com/proto/1hT5X43DR8KCuFFZEFlMV4/%F0%9F%9B%AB-Onboarding?page-id=715%3A5567&node-id=715%3A5568&viewport=344%2C48%2C0.5&scaling=min-zoom&starting-point-node-id=715%3A5568&show-proto-sidebar=1) and [file](https://www.figma.com/file/1hT5X43DR8KCuFFZEFlMV4/%F0%9F%9B%AB-Onboarding?node-id=715%3A5568) and the required changes are:

- [x] Change the order of steps
- [x] Update copy of call to actions
- [x] Add tooltips and arrow icons to last two steps
- [x] (Popup) Reduce heading size to Label02 so that text fits better

**Comment by Eshwari007** [comment]
Quick note: Only fresh install and new wallet accounts have the next steps. Though it's a new wallet/account and not upon the fresh install of the extension, the next steps will not be visible.
Just noting down the behavior above for future tracking purposes.

**Comment by Eshwari007** [comment]
Note:
`Check off steps when the step has been completed or the URL has been visited`-This was tested locally by @fbwoolf as there was a bug identified.https://github.com/hirosystems/stacks-wallet-web/issues/2328
Will be testing MoonPay upon whitelisted and verifying if the step along with `Buy an NFT` was successful.

**Comment by markmhendrickson** [comment]
@Eshwari007 Have you QA'ed event tracking for these changes? E.g. for when the user clicks on each next step option.
