### ISSUE TITLE
transaction rejected - TooMuchChaining

### ISSUE THREAD

**Issue by friedger** [leather-io/extension#1482]
When I try to submit a transaction an error is shown:
```
There was an error when broadcasting this transaction:
transaction rejected - TooMuchChaining
```
The error does not provide any indications how to resolve this issue.

This happens on mainnet using stacks-node-mainnet.stacks.co endpoint.

The account's nonce shows: 2

**Comment by aulneau** [comment]
@zone117x this seems to be occurring more frequently, and it's not something i'm super familiar with. Do you know what would cause this?

**Comment by zone117x** [comment]
`TooMuchChaining` is returned when more than 25 txs from a given account are already waiting in the mempool. See:
https://github.com/blockstack/stacks-blockchain/blob/85f07f1aa74638458ac118627477d05936994841/src/chainstate/stacks/db/blocks.rs#L5321-L5340

If it's occurring more frequently, is it the case that you're often ending up with more than 25 txs during a given epoch?

**Comment by diwakergupta** [comment]
@friedger I'm not sure there's anything actionable here for the wallet (besides the issue about persisting messages that @aulneau already opened). Can we close this?

**Comment by markmhendrickson** [comment]
Note here's the related issue from @aulneau: https://github.com/blockstack/stacks-wallet-web/issues/1498

**Comment by 314159265359879** [comment]
I have had this happen too, it looks like it is carried over from accounts when using several public keys on the same private key.
The only way I was able to resolve this was by uninstalling the extension and trying on an other machine.

After sending about five transactions today on one private key but several public keys they started failing with the same nonce. This one is still in the mempool via pool.friedger.de which both got a nonce higher than the account nonce (in this example tx nonce 7 account nonce 5) (I also send 50 stx on an other account that also got nonce 7 instead of 4)

https://explorer.stacks.co/txid/0xebe4e17707b863d4fb3ae49e170cb03dd480a1f6faf266cd6654e69689c9b74c?chain=mainnet

After wab wallet logout login I nolonger get the TooMuchChaining error but ai still get the wrong nonce 8 instead of 5
Tx: 0x6a3d77e864b5e7a68da7b11c0c6f4bbf53ffc90adc40bc742781955f33b579ee

And after reinstalling the extension clearing site cache, restarting chrome still a nonce error. Maybe I need to wait for them to clear the mempool?

**Comment by 314159265359879** [comment]
I tried repeating a transaction from an other browser. Yesterday failed with nonce 7 instead of 4. Firefox transaction today already confirmed.

**Comment by markmhendrickson** [comment]
@314159265359879 the work being done on https://github.com/blockstack/stacks-wallet-web/issues/934 appears more relevant to the nonce issues you're encountering.

My guess is that the TooMuchChaining error instance in your case was resolved because the new install didn't encounter the caching issue getting addressed here: https://github.com/blockstack/stacks-wallet-web/issues/1498
