### ISSUE TITLE
Add BTC wallet support

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#1483]
Allow users can access the BTC stored with the same Secret Key.

This was requested by the [PlanBetter](https://planbetter.org/) team, which currently sends BTC to the key's underlying address but has to direct users to Electrum to withdraw the funds.

This could be helpful for Stacking applications in general for the creation of a consolidated UX around BTC, STX and Stacks-based apps. This doesn't have to be a separate wallet in the UX per se but rather an additional assets balance alongside chain-native assets.

**Comment by andresgalante** [comment]
Do we have anyone asking for this feature?

**Comment by 2snEM6** [comment]
In my opinion, there are many ways on why this feature is positive for the Stacks Wallet Web and also for the Stacks Ecosystem.

- It helps bring STX and BTC tokens even closer, under the same interface. Users could have BTC within the same wallet classified as an additional asset.  (And maybe in the future even swap them using @friedger new decentralized btc-stx swaps)
- Stacking pools that reencode STX addresses into BTC addresses and send stacking payouts to those, would mean stackers would see BTC payouts directly in their wallets, without having to use external explorers, or wallets, making the user experience smoother and also contained within the same domain.

**Comment by friedger** [comment]
Is this about read-only access to BTC wallets or also to create and sign txs? I would imagine that a full-fledged BTC wallet is out of scope.

**Comment by markmhendrickson** [comment]
The PlanBetter team requested this when we met with them recently, and I believe @xanbots has requested this in the past (though my impression is that it's less relevant to Daemon plans these days).

My impression in both cases as well was that a full-fledge BTC wallet was desired so users – either Stacking pool users or mining pool users in these respective cases – could manage STX and BTC with sends and receives with one holistic solution / in one place with the same underlying key.

**Comment by pors** [comment]
> My impression in both cases as well was that a full-fledge BTC wallet was desired so users – either Stacking pool users or mining pool users in these respective cases – could manage STX and BTC with sends and receives with one holistic solution / in one place with the same underlying key.

What is meant here with the same underlying key? To use the same HD wallet phrase for both STX and BTC?

**Comment by markmhendrickson** [comment]
> What is meant here with the same underlying key? To use the same HD wallet phrase for both STX and BTC?

@pors Yep the same phrase for both types of holdings

**Comment by markmhendrickson** [comment]
@xanbots indicated yesterday that this is still indeed relevant to their plans at Daemon

**Comment by markmhendrickson** [comment]
@beguene want to post a consolidated version of your tech spec here as a comment, migrating it from Notion for greater transparency and easier reference as we start work on this?

**Comment by landitus** [comment]
Last week we had an initial project kick-off where we brainstormed around the most basic ways to integrate Bitcoin into the wallet. During the session we touched upon displaying BTC/STX addresses, viewing balances/activity, sending and receiving BTC and how to handle network selection for both Bitcoin and Stacks networks. The network part seems the more tricky, since there are 2 networks to choose from and there could be some confusion around combining testnet and mainnet networks from both blockchains at the same time.

There will be mockups coming exploring these ideas soon:

[Figma](https://www.figma.com/file/EjbD9ZoMlp7okjvFMKObfA/BTC-ideas?node-id=0%3A1)
![Image](https://user-images.githubusercontent.com/239215/169846500-da4e58ce-8f2a-4d6d-aeb6-7670d4020d67.png)

**Comment by 2snEM6** [comment]
This is great news! One thing that would be interesting to consider is the capability for a client application to interact with the wallet via Stacks.js, in order to trigger a bitcoin transaction programatically. 

I foresee two different ways:

1. The client application uses a programmatic interface to signal the Stacks Web Wallet to spend BTC => the Stacks Web Wallet opens the Send Bitcoin screen with pre-filled details (address, amount, etc).

2. The client application uses a programmatic interface to signal the Stacks Web Wallet to spend BTC => the Stacks Web Wallet opens the Send Bitcoin application but it is up to the user to choose the amount, the recipient address, etc.



> 1. The client application uses a programmatic interface to signal the Stacks Web Wallet to spend BTC => the Stacks Web Wallet opens the Send Bitcoin screen with pre-filled details (address, amount, etc).

This approach opens up many possibilities, for instance to stacking pools that encode Bitcoin addresses from Stacks addresses and are already aware of the constraints users might have when building a Bitcoin transaction since they handle it in app: address, amount, or even fees. However the Stacks Web Wallet would need to verify this data before prompting the user to sign the transaction.

> 2. The client application uses a programmatic interface to signal the Stacks Web Wallet to spend BTC => the Stacks Web Wallet opens the Send Bitcoin application but it is up to the user to choose the amount, the recipient address, etc.

This other approach is simpler and more constrained, since the Stacks Web Wallet would be the only responsible of allowing the user to select amount, address, etc. As it is more constrained, use cases such as the above would cause worse UX, IMO.

**Comment by markmhendrickson** [comment]
Some exploratory designs are now available [here](https://www.figma.com/proto/OSQocEEJnfcMkniEl8u3U8/%231483---Initial-Bitcoin-support?page-id=207%3A38522&node-id=259%3A44780&viewport=370%2C1438%2C0.25&scaling=scale-down&starting-point-node-id=259%3A44780&show-proto-sidebar=1) in a Figma prototype.

## Home

<img width="292" alt="image" src="https://user-images.githubusercontent.com/28991/182158767-cde3b96c-015d-4c26-ae23-4360036cf077.png">

## Receive

<img width="282" alt="image" src="https://user-images.githubusercontent.com/28991/182158827-868075bc-d843-44e0-b260-30ee5617d306.png">
<img width="277" alt="image" src="https://user-images.githubusercontent.com/28991/182158859-589fe8bf-6074-4dd8-89e7-ec5a6922c724.png">

## Switch account

<img width="281" alt="image" src="https://user-images.githubusercontent.com/28991/182158984-16a40967-ce78-4841-b1f6-d8fdb292e9ca.png">

## Choose account

<img width="311" alt="image" src="https://user-images.githubusercontent.com/28991/182159037-996c2d9c-e35b-453f-9989-dc03cba24da9.png">

**Comment by markmhendrickson** [comment]
We're now tracking sub-issues for this feature on [the board](https://github.com/orgs/hirosystems/projects/9) under this new milestone: https://github.com/hirosystems/stacks-wallet-web/milestone/63

**Comment by markmhendrickson** [comment]
This is now live, along with Ordinals! https://twitter.com/hirowallet/status/1627706760332214274
