### ISSUE TITLE
[2.15.0] chrome wallet password minimum length 17 instead of 12

### ISSUE THREAD

**Issue by 314159265359879** [leather-io/extension#1638]
In this flow
1. type in key phrase
2. type in short password of 12 chars including two words (four letters each), 2 numbers and two symbols (birdbird12!@)
3. you still get this:
![image](https://user-images.githubusercontent.com/33360391/131384526-6bf56364-e96c-40a9-9e05-9ff2b08fbe5f.png)
4. and you can not pass until you have extended the password with 5 more characters. 

Changing the password to bird12bird!@ (12 characters) will pass you through to the next step. I think birdbird12!@ should likewise pass or should neither because it is not more then 12?. I think the number should mentioned here should be the target number "wording use atleast 12 characters" because that makes it easier for the reader to interpret (they will only read the number). 

Bug originally found by ToTheMoon on Discord, I did some additional testing hoping it will help resolve this:
![image](https://user-images.githubusercontent.com/33360391/131385007-a622300e-5368-4857-b61d-78d9b62f767c.png)

**Comment by kyranjamie** [comment]
The wallet uses [zxcvbn](https://github.com/dropbox/zxcvbn) which uses an algorithm to determine strength, rather than exact numbers of symbols or characters. 

So the requirement is more than 12 **and** strong enough determined by zxcvbn. The copy here is very confusing, though. We have [plans to improve this very soon](https://github.com/blockstack/stacks-wallet-web/issues/1476).
