### ISSUE TITLE
Add option for developer and PBC to receive app usage stats

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#291]
Developers and PBC alike would benefit from knowing how much usage apps get on a daily, weekly or monthly basis. At the same time, it's paramount that the platform never collect PII information about its users.

This issue entails adding an option for developers to enable stats for either just themselves or themselves plus PBC.

The stats would entail consist simply of the number of unique visitors to the app on a given day, week or month. They would not consist of any PII information such as IP address tracked by analytics packages. 

One approach may be to have Blockstack Connect store client-side all of the user's device specific visits and report only once per active day via API calls to servers run by the developer and PBC just what day, week and month they've loaded the app.

Clients would be trusted in this model to self-report accurately and the server component may need some simple mechanisms in place to filter out false positive reports. But the model would be largely a trust-based one in that clients are trusted to report their activity accurately, shifting the responsibility to them instead of the servers where PII would otherwise be needed to identify unique users.

@hstove assigning this to you for initial review

**Comment by hstove** [comment]
This is an interesting thought experiment, and one we should involve our community devs in.

A precursor for this is some kind of PBC self-hosted analytics service. Mainly we want something where we own the database, so that it's easy to report aggregated numbers. This will be much harder to do if we rely on services like Segment or Mixpanel, which are not built to easily serve custom queries directly from their database.
