### ISSUE TITLE
New auth and an existing id results in "Bad Request  Request Line is too large (4209 > 4094)"

### ISSUE THREAD

**Issue by laytond** [leather-io/extension#318]
This only seems to be happening while using the new auth on Webby _(i.e. it didn't appear when trying Banter)_, but attempting to use my "layton.id" Blockstack account results in the following error: "**Bad Request** Request Line is too large (4209 > 4094)"
![image](https://user-images.githubusercontent.com/10748468/78584531-31855e80-77ed-11ea-8fe3-2b034817eeca.png)

Any/all of my "id.blockstack" accounts work fine.

_Update while writing this ticket:_ If I keep trying over and over again in fairly quick succession, eventually my layton.id account will log in. But logging out and trying again will reproduce error.

**Comment by laytond** [comment]
Note: Dan T didn't have any issues while using his .id accounts. So maybe this is just my account?

**Comment by dantrevino** [comment]
I just ran across this same error when testing out implementation of connect on Land Ho.  https://landho-daily.runkodapps.com

Note that authentication seemed to succeed, which may be more concerning?

![Screenshot_20200407-105847_Brave](https://user-images.githubusercontent.com/7738/78704383-a2497b00-78c0-11ea-82e2-24882b5a7884.png)

**Comment by markmhendrickson** [comment]
Thanks guys, and sorry for the delay here. Assigning over to @hstove so he can take a look.

**Comment by hstove** [comment]
Unfortunately, this is something that'll have to be fixed on your app's side. Whatever web host you're using is limiting the max size of headers. Depending on how you're hosting, you should be able to fix this configuration.

What's odd is that we're constructing the `authResponse` in the same way as the Blockstack Browser handles it - but it sounds like you're not seeing that error there? Maybe there is some extra info we're sending, because the header is only 100 chars longer than your server's max.

**Comment by dantrevino** [comment]
Both of these are hosted on Runkod.  @talhasch is this something that you can take a look at?

**Comment by talhasch** [comment]
@laytond @dantrevino I've made some server updates. Can you check again?

**Comment by dantrevino** [comment]
Sorry for leaving this open. It was fixed.

**Comment by laytond** [comment]
Yeah not seeing this anymore, thanks! Closing it out.
