### ISSUE TITLE
Metric collection around TX signing

### ISSUE THREAD

**Issue by hstove** [leather-io/extension#395]

**Comment by markmhendrickson** [comment]
Want me to lay out the exact event names and their properties to implement?

**Comment by hstove** [comment]
I added this on Friday, you can see the names [in this commit](https://github.com/blockstack/ux/pull/301/commits/39a126e00f4457d31abf334f6fa714ef96332d3e).

**Comment by markmhendrickson** [comment]
Which Segment source is configured for [the demo app](https://authenticator-demo.netlify.app/), which I assume is the best place to QA these metrics? I'm not seeing events in [this one](https://app.segment.com/blockstack/sources/authenticator/overview) or [this one](https://app.segment.com/blockstack/sources/authenticator_development/overview). 

I presume we'd want to instrument the latter one since we're in developer preview for this functionality, but we may also want to set up a new Segment source entirely.

**Comment by hstove** [comment]
We don't have Segment in the demo app itself - just the authenticator. The authenticator metrics should be in the production source, I'm pretty sure.

**Comment by markmhendrickson** [comment]
This issue _is_ actually about putting metrics around TX signing so we should test to make sure that events are coming through for each action taking during the new TX signing flows.

**Comment by timstackblock** [comment]
@markmhx @hstove  

The events are being logged as expected

![Screen Shot 2020-06-15 at 9.57.37 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/6fad2b26-833b-4efc-a13e-cd0c9e6df8cd)
