### ISSUE TITLE
Clicking on Chrome extension icon in menu bar loads missing page

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#442]
<img width="1282" alt="Screen Shot 2020-06-19 at 18 10 11" src="https://user-images.githubusercontent.com/28991/85154787-31c3c080-b258-11ea-8411-bb833b0dd87e.png">

**Comment by hstove** [comment]
This one is pretty odd - @timstackblock , have you ever seen this?

My assumption is this is caused by some messing around with your local extension files in some way. I'm not sure how else this file could just "disappear" 🤷 .

Try doing a clean reinstall of the extension, using the latest CircleCI version, and then see what happens?

**Comment by markmhendrickson** [comment]
I'm not seeing the `test_web` CI job in this PR now to get the latest extension and re-rest https://github.com/blockstack/ux/pull/385

**Comment by timstackblock** [comment]
Is this the same version of the extension that I am using? The extension ID is different from the one in my browser and this works for me see the image below. I cannot reproduce this.

@hank is there a new version I should be using or is the last one you sent to me the correct one?

![Screen Shot 2020-06-22 at 9.43.49 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/21b8adf2-90c1-492e-b93f-c32d7032ac7c)

**Comment by timstackblock** [comment]
The icon is removed for me

![Screen Shot 2020-06-23 at 11.20.49 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/3ea2f0e8-743b-48ea-98db-69aa7dd71e8c)
