### ISSUE TITLE
[connect] finished callback fires multiple times

### ISSUE THREAD

**Issue by aulneau** [leather-io/extension#444]
In working with the explorer, I have determined that the finished callback can get called many times. I wonder if we can debounce or throttle it from within connect? There are ways for app devs to prevent this, but seems to be an underlying issue with connect.

**Comment by hstove** [comment]
Yep, I think this will definitely happen if you open the popup more than once, especially if you manually close one of them. A few things here that would help:

- Detecting that the popup was closed, related to what we've talked about with firing a callback for this. I think this is the root issue, because Connect doesn't clear its listener until after the popup was successful.
- Using `window.opener.postMessage` instead of the message polling technique we're doing at the moment

**Comment by aulneau** [comment]
Just to note, the definitely happens with only one window open event.

**Comment by aulneau** [comment]
this is a much larger issue that i'll break out into smaller tasks
