### ISSUE TITLE
User login hangs after first entering secret key

### ISSUE THREAD

**Issue by john-light** [leather-io/extension#538]
After clicking "I already have a secret key" on Sigle, and entering my secret key in the Blockstack App, I am shown a couple of names owned by the secret key. I click on one of the names to use with Sigle, and the app just hangs there loading forever. If I close the Blockstack App pop, then try again, then it works. See demo here:

https://www.youtube.com/watch?v=E9JfhiYirzk

Browser: Firefox 78.0.2
OS: Linux Mint 18.3

**Comment by markmhendrickson** [comment]
Thanks for this report, John. Any chance there's something indicative in the app window's console?

**Comment by john-light** [comment]
Immediately after entering secret key, first auth attempt:

![blockstack1](https://user-images.githubusercontent.com/9424721/88347014-bd2ce780-cd17-11ea-95fa-a8b8e313b945.png)

After closing the window and trying again, second auth attempt:

![blockstack2](https://user-images.githubusercontent.com/9424721/88347092-e3eb1e00-cd17-11ea-8fba-552aa3c1c679.png)

**Comment by markmhendrickson** [comment]
@hstove any ideas here given the "No auth request found" messages in the logs?

**Comment by hstove** [comment]
Apologies for not responding earlier.

There have been some changes to this flow since the issue was reported. One possible cause is if Sigle is not passing the `redirectTo` flag during authentication. This would prevent the redirect fallback from being triggered.

The 'no authRequest found' message is not 100% a bad thing - based on the code flows here, the authRequest is stored in local memory during auth, instead of in the URL param. I could look into removing this message in that case, as I can see that it could be confusing. There definitely _is_ some authRequest state here, which is how we display things like "Login to Sigle"

**Comment by markmhendrickson** [comment]
I'm closing this out as stale. Please re-open if needed. 

@pradel you may want to take a look here as well in case any relevant changes to Sigle are still needed.
