### ISSUE TITLE
New name for "Blockstack App" extension

### ISSUE THREAD

**Issue by john-light** [leather-io/extension#550]
I think the "Blockstack App" browser extension could use a new name. Mainly because it can get confusing when I'm talking about using Blockstack apps (i.e. apps built using Blockstack) with the Blockstack App (a browser extension for authenticating to Blockstack apps).

Some ideas:

- Blockstack  
- Blockstack Auth  
- Blockstack Login

**Comment by markmhendrickson** [comment]
I agree the name could use improvement, and since [Blockstack PBC will be changing its name](https://forum.blockstack.org/t/the-stacks-ecosystem-focusing-the-brand-on-what-brings-us-together/11009) and dropping the use of "Blockstack" in general soon, we can't keep calling it "Blockstack [anything]", anyway.

One idea I've floated recently is [hosting the app on App.co and having it adopt the domain's name ](https://github.com/blockstack/ux/issues/543)("App.co").

The main advantage there would be keeping the name generic and "app"-oriented, since it itself is an app _and_ it's likely to evolve into a portal for discovering, authenticating and managing Stacks-based apps as well.

A challenge in this approach, though, would be calling the _extension_ "App.co" since you don't have to visit app.co to use the extension obviously.

We could call it something with "auth" or "login", since that's what it does mainly at the moment. But if it does gain app discovery and management – plus wallet / STX management functionality – then we're likely to find the name limiting.

Another way to go about this may be to adopt a word without default significance like "MetaMask" since we can then imbue it with whatever meaning / functionality the app gains over time.

**Comment by john-light** [comment]
I missed the post about consolidating around the Stacks branding. Maybe the extension could just be called Stacks then ("the Stacks browser extension") or Stacks Wallet or something like that. I also like the idea of giving it its own unique name a la MetaMask, but if this extension is likely to be people's first touchpoint in the Stacks ecosystem maybe it makes sense to keep the branding Stacks-centric to reinforce the extension's relationship to the Stacks ecosystem and brand. Just some ideas, no strong feelings either way :)

**Comment by markmhendrickson** [comment]
We have since renamed the extension to "Stacks Wallet": https://www.hiro.so/wallet/install-web
