### ISSUE TITLE
enhancement: add anti-phishing phrase feature to Connect

### ISSUE THREAD

**Issue by fluidvoice** [leather-io/extension#556]
details on the forum here: https://forum.blockstack.org/t/try-out-the-new-streamlined-authenticator-with-blockstack-connect-beta/10382/78?u=fluidvoice
"... Basically the user would be prompted for some word or phrase that would be displayed prominently in the GUI on subsequent auth attempts, so the user would easily notice if the auth GUI was fake."... 

Does it make sense? Can it be done?

**Comment by friedger** [comment]
Also support for password managers might help if the user has stored the pass phrase in a password/passphrase manager. (Is the use of a manager here something that is desirable?)

**Comment by fluidvoice** [comment]
> Also support for password managers might help if the user has stored the pass phrase in a password/passphrase manager. (Is the use of a manager here something that is desirable?)

There are a couple of Blockstack auth dapps that do password managing.  I don't know how good they are (yet) and if they are completely open source (trustworthy).  So is the question if this functionality should be rolled into Connect or kept as a separate app?  Maybe there is an advantage to the Blockstack team doing the first version of this - for trust reasons - and it gets taken over by open source contributors over time.  Making this feature optional via config or toggle?

**Comment by fluidvoice** [comment]
Dan made a comment why not just use 2FA?  If it can be done, I think an anti-phishing phrase is better for UX because 2FA requires using another app and data entry _every time_ an auth/login takes place, slowing down the auth process. While the anti-phishing phrase is created only once (or say once a month if it's made with expiration) and the users just sees it in the UI every auth/login attempt.

**Comment by MarvinJanssen** [comment]
@friedger I already use a password manager (Bitwarden) to manage some Blockstack seeds. I do not think explicit support is necessary since most password managers inject it into the page when requested.

@fluidvoice Anti-phishing phrases are good in theory but as you stated on the forum, storing them securely is the problem. I do not currently know of a way to do it.

However, it could be possible to do a round-trip via Gaia from another device, which is something an attacker cannot fake. For example, the authentication flow could present the user with a QR code which is to be scanned by a dedicated (mobile) app. The QR code contains the app domain and an ephemeral key. The app then encrypts information using the key and stores that on Gaia, perhaps in profile storage. The dapp discovers the encrypted data through some mechanism (hash of the app domain perhaps) and thus completes the sign in process.
