### ISSUE TITLE
User session in payload?

### ISSUE THREAD

**Issue by njordhov** [leather-io/extension#581]
Several functions in Connect inject the `userSession` in the payload/token due to the `...opts` spread: `makeContractDeployToken`, `makeContractCallToken`, `makeSTXTransferToken`. 

Is the `userSession` really supposed to end up in the url query? Seems like it could become a security risk.

https://github.com/blockstack/ux/blob/3f46f600cccfeadca381574b2b493709b4bba590/packages/connect/src/transactions/index.ts#L90-L105

**Comment by hstove** [comment]
Good catch @njordhov ! Yes, you could consider this a security issue when using the hosted authenticator, as the token could technically be intercepted. I wouldn't say it's a very critical vulnerability, because the hosted authenticator is already trusted with your entire seed phrase. However, this is a great suggested change, even just to strip out junk from the request token.
