### ISSUE TITLE
Conflicting nonce in mempool

### ISSUE THREAD

**Issue by dantrevino** [leather-io/extension#594]
Trying to create an openSTXTransfer() call for the same recipient, different amount, and the 2nd transactions fails with 'transaction rejected - ConflictingNonceInMempool' error, but there is no option to set a nonce, so I'm expecting the library to be handling this.

![image](https://user-images.githubusercontent.com/7738/93296398-f3c93080-f7a3-11ea-9cfe-67056271622d.png)

**Comment by psq** [comment]
Connect adds the right nonce, for the first transaction, but uses the same one twice (it queries the node to figure out what is the nonce value, but the result returned by the server will return the same value till that transaction has been processed).  So the first transaction gets accepted, but the second, using the same nonce gets rejected.

Due to https://github.com/blockstack/stacks-blockchain/issues/1417 and https://github.com/blockstack/stacks-blockchain/issues/1719, you can not send more than one transaction per block per sending address.

Once these are addressed, Connect will need an option for you to set the nonce, or Connect will need to set increasing nonces on its own, which gets tricky if more than one client needs to send transaction from the same address.

Currently, even if you were setting the nonces correctly, only the first transaction would get accepted.

**Comment by markmhendrickson** [comment]
This is related to https://github.com/blockstack/ux/issues/530. Thanks for the report and info @dantrevino and @psq 🙏

**Comment by dantrevino** [comment]
Thanks @psq @markmhx. Closing this since its tracked in #530
