### ISSUE TITLE
FF extension doesn't open app after sign in, pops another browser tab but app is not logged in

### ISSUE THREAD

**Issue by timstackblock** [leather-io/extension#623]
The mozilla FF extension doesn't open/login to the app after the user completes sign in, it just pops another window/tab but app is not open or logged in.

Video of the issue HERE http://somup.com/cY6i21lZAf

<img width="1434" alt="Screen Shot 2020-10-07 at 10 09 30 AM" src="https://user-images.githubusercontent.com/49165468/95342441-6f8b3a00-0885-11eb-9e3f-4e8cc8e5c370.png">
<img width="1422" alt="Screen Shot 2020-10-07 at 10 10 02 AM" src="https://user-images.githubusercontent.com/49165468/95342443-7023d080-0885-11eb-9529-ce636926f079.png">
<img width="1432" alt="Screen Shot 2020-10-07 at 10 09 43 AM" src="https://user-images.githubusercontent.com/49165468/95342445-70bc6700-0885-11eb-8526-b042da3b8e0d.png">
<img width="1429" alt="Screen Shot 2020-10-07 at 10 10 16 AM" src="https://user-images.githubusercontent.com/49165468/95342449-7154fd80-0885-11eb-8f53-dcab34bb3c6d.png">

**Comment by markmhendrickson** [comment]
The Pravica team has reported this issue in production as well: https://drive.google.com/file/d/1R7vo_-PGCwzyE7_062yEXvkpjJzVtZfd/view?usp=sharing

**Comment by hstove** [comment]
Interesting issue. I am unable to replicate this in Firefox with the extension installed, using the testnet demo app.

There is the issue that Firefox is always opening a new tab after authentication, when you have the extension installed. It turns out that Firefox doesn't allow the kind of message passing we're doing with an extension. There are different mechanisms we could use, but it requires much further refactoring. It would be a good thing to do when we consolidate around extensions, as they all allow a more powerful API than is available on both hosted and extension.

For Pravica, they are getting redirected with an authRequest, so I'm not sure why the user is not being logged in. I'd have to see their front-end code for handling redirect authentication.

**Comment by timstackblock** [comment]
Still getting the error I took a new video here is a screen shot of the extension version as well.

See video here: http://somup.com/cY6rrdlLll

<img width="1438" alt="Screen Shot 2020-10-21 at 5 44 16 PM" src="https://user-images.githubusercontent.com/49165468/96791177-fa138380-13c5-11eb-8e3a-d2dee86e7829.png">

**Comment by hstove** [comment]
@timstackblock can you check console logs? Inside of the testnet demo app?

**Comment by timstackblock** [comment]
Sure the first screen shot is the original window and the second is the new tab that opens.

<img width="1440" alt="Screen Shot 2020-10-22 at 1 50 52 PM" src="https://user-images.githubusercontent.com/49165468/96910640-cb50e800-146d-11eb-877a-67b231fee037.png">
<img width="1439" alt="Screen Shot 2020-10-22 at 1 51 05 PM" src="https://user-images.githubusercontent.com/49165468/96910641-cbe97e80-146d-11eb-9473-9102b860bd15.png">

**Comment by hstove** [comment]
This appears to be an issue with the state of this page - are you reloading the extension and then attempting to log in right away? Stuff like that can mess with things. The first error message is expected, and the second error message is unrelated to the changes from this PR - it happens from multiple auth sessions in flight, or when messing with reloading the extension.

Could you try it from a clean slate? I.e. hard refresh the testnet demo app and then try again? Sorry to bug you with these requests.

**Comment by timstackblock** [comment]
Sure no problem let me try it again

**Comment by timstackblock** [comment]
Yup that seemed to work I force quit Firefox the re-opened the app and now its working.

**Comment by markmhendrickson** [comment]
@timstackblock let's close this out if loading the page after the latest extension install or enable essentially fixes this?

**Comment by timstackblock** [comment]
Sure, I am ok with closing this out. Lets just monitor support tickets, if this happens in prod we can tell people to quit the browser and re open it.

**Comment by markmhendrickson** [comment]
I'm still seeing this issue on both Pravica and Testnet Demo with v1.0.0:

![Kapture 2020-11-02 at 14 07 42](https://user-images.githubusercontent.com/28991/97871441-cd8c2f80-1d14-11eb-9325-ac2d5a1f92c2.gif)

Note there is nothing in the console logs for either resulting tabs.

**Comment by timstackblock** [comment]
@markmhx I was still seeing it as well when I had my FF browser open, then @hstove had me close out the browser and reopen it I also did a hard refresh and everything worked fine.  Can you try that and see if it works?

**Comment by markmhendrickson** [comment]
Hmm I've since removed the extension and tried to reinstall from source but ran into these problems: https://github.com/blockstack/ux/issues/656.

And the extension also disappeared from the add-ons store so I can't install it from there either per https://github.com/blockstack/ux/issues/652.

I understood @hstove to recommend a hard refresh (which I did previously, to no avail) though not a browser restart necessarily. That said, I _was_ testing the extension with both apps having opened Firefox anew with the extension already installed. So I don't see how re-installing the extension, restarting Firefox and hard refreshing will help necessarily? It was working from such a "clean slate" anyway.

**Comment by markmhendrickson** [comment]
I tested this again and authenticating with the latest Firefox extension as built from source still hangs for me upon selecting an account / username.

@timstackblock can you try recreating again?

![image](https://user-images.githubusercontent.com/28991/99962514-9d263700-2d90-11eb-981e-165cafed5807.png)

**Comment by timstackblock** [comment]
I am able to recreate this issue as well moving this back to dev

**Comment by markmhendrickson** [comment]
This appears to work for me in the latest build found on https://github.com/blockstack/ux/pull/731

@timstackblock want to retest?
