### ISSUE TITLE
Unexpected login / logout behavior

### ISSUE THREAD

**Issue by whoabuddy** [leather-io/extension#678]
I am still trying to recover my 3rd username to use with Connect as documented in #626, and today I tried logging out of https://app.blockstack.org and planned to log back in.

However, after doing so, I'm not sure the best way to sign back in to app.blockstack.org?

Should there be a way direct way to log back in, or only through another app?

Should other apps be signed out as part of this action?

More details below, including steps to recreate:

1. Click "Log Out" on https://app.blockstack.org, which presents the message "Your are now signed out" and links to https://app.co/blockstack
![20201113_002_Selection](https://user-images.githubusercontent.com/9038904/99087821-72660280-2588-11eb-8f09-f0dd471193ab.png)
1. Click on the link to https://app.co/blockstack
1. Click on the link to an application using Connect
    - first one I tried was BlockSurvey
    ![20201113_003_Selection](https://user-images.githubusercontent.com/9038904/99088119-d5579980-2588-11eb-8aed-9046833a1ba6.png)
    - second one I tried was Sigle
    ![20201113_004_Selection](https://user-images.githubusercontent.com/9038904/99088134-da1c4d80-2588-11eb-8ded-f7409004b1d0.png)
    - as shown in the screenshots above, the last-used account is still logged in
1. Navigate back to https://app.blockstack.org which still shows "You are now signed out".

Following that, if I log into another service using Connect that I was not previously authenticated against, such as https://heywebby.app/ then it works as expected. After that, refreshing https://app.blockstack.org shows my user names.

*note: the third username is still missing*

**Comment by markmhendrickson** [comment]
Currently you can initiate authentication for Connect / the hosted authenticator only through an app, not from the authenticator's homepage, as you've found here. 

However, as we work towards 2.0, we're adding the capability to authenticate outside of the context of an app with https://github.com/blockstack/ux/issues/673. So there will be less dependency on apps in this regard to kick things off.

On the flip side, when you sign out of the authenticator itself, it doesn't de-authenticate apps. That's a separate process that a user needs to take with those individual apps and is intentional.

We don't have any plans in 2.0 to change this behavior (and I'm not even sure how feasible or desirable this would be given the overall model of decentralized authentication).
