### ISSUE TITLE
STX transfer not possible from test app

### ISSUE THREAD

**Issue by friedger** [leather-io/extension#749]
Using Debugger -> Stx transfer on https://pr-725.testnet-demo.stacks.engineering/ results in an empty screen on the hosted web version.

I am using ubuntu and firefox or chrome

Firefox:

![Screenshot from 2021-01-08 22-08-22](https://user-images.githubusercontent.com/1449049/104064335-13c2ab00-51fe-11eb-87a7-cf28116bca39.png)

Google Chrome:

![Screenshot from 2021-01-08 22-12-30](https://user-images.githubusercontent.com/1449049/104064672-a2cfc300-51fe-11eb-8733-878a731a4e3e.png)

**Comment by markmhendrickson** [comment]
I just tried this and it worked for me fine: https://testnet-explorer.blockstack.org/txid/0xf1dc3c196b178de20277ea2ef054e043f2a6b0cf4ee43a66415de350338017d6?chain=testnet

![image](https://user-images.githubusercontent.com/28991/104118516-099dcb00-532a-11eb-9033-455ccaf90244.png)

I'm on MacOS in Chrome.

@friedger What happens if you visit https://pr-725.app.stacks.engineering/? Does it recognize that you're signed in? The error in your screenshot suggests that there's no session with the hosted wallet.

**Comment by dantrevino** [comment]
I'm getting transaction rejected and NotEnoughFunds errors with OpenSTXTransfer from Boom.  My sending account has enough ... confirmed on https://pr-725.app.stacks.engineering/ see screenshots and walkthrough (google drive url at teh bottom).

![image](https://user-images.githubusercontent.com/7738/104148912-0ab21500-5389-11eb-9885-7e0363c28169.png)

![image](https://user-images.githubusercontent.com/7738/104149021-90ce5b80-5389-11eb-86c4-d70213ce5e49.png)


https://drive.google.com/file/d/17Td9wufzb_l59EPspvIn4UFXmJXiQBin/edit

**Comment by markmhendrickson** [comment]
@hstove any ideas about the above?

**Comment by dantrevino** [comment]
These appear to be using a non-first identity.  Calls directly to the stacks api or getAccountBalance in the SDK will return a balance, but submitting a transaction fails with Not Enough Funds error ... submitting transactions appears to be using only the *1st* identity in your identity wallet. Discussion in discord had options, but commonly expected behavior is that when you log in with an ID, all of your transactions should be submitted with that same ID.

**Comment by markmhendrickson** [comment]
`when you log in with an ID, all of your transactions should be submitted with that same ID` -> that's been my expectation as well. @hstove are you approaching this differently?

**Comment by timstackblock** [comment]
I encountered a infinite spinner when using firefox, it works well in chrome for me but I have had problems with transaction signing in FF https://github.com/blockstack/ux/issues/776

@dantrevino what browser are you using?

**Comment by dantrevino** [comment]
Using chrome 86.0.4240.199 (64 bit) on ChromeOS

**Comment by hstove** [comment]
I've made changes here to at least show your current account and balance on the TX signing page. We also now show an error if you are trying to STX transfer with not enough funds, before you send it. I have not been able to reproduce any errors that aren't relating to this kind of thing, though.

**Comment by markmhendrickson** [comment]
@hstove Should @dantrevino and @timstackblock retest this with a particular PR?

**Comment by hstove** [comment]
If you use the test app via https://pr-761.testnet-demo.stacks.engineering/, it'll direct you to the install page on `hiro.so`. That's the best way to install the extension at the moment. But yes, we should always refer to #761 as the latest right now, where this should definitely be fixed.

**Comment by timstackblock** [comment]
I am still seeing the same issue as @dantrevino 

<img width="1427" alt="Screen Shot 2021-01-25 at 11 56 11 AM" src="https://user-images.githubusercontent.com/49165468/105737956-858c3b80-5f04-11eb-8e11-88d44ab58cc0.png">

**Comment by hstove** [comment]
I'm confused about what the issue is. I understand that we could show the error before you send, but it appears that you don't have enough STX. Is that not true? Or are you saying that the popup doesn't open to the same address you logged into the app with? That should have been fixed on Friday, but if it's not, LMK.

**Comment by timstackblock** [comment]
This works please see the video of me doing a STX transfer with the extension on the test app

VIDEO: http://somup.com/crVObVogGn
