### ISSUE TITLE
Resolve conflicting nonce issues

### ISSUE THREAD

**Issue by dantrevino** [leather-io/extension#934]
I'm able to reliably replicate creating a conflicting nonce error by:
1. create a transaction to yourself
2. let it fail (recipient cant be sender)
3. create another transaction to someone else

**Comment by dantrevino** [comment]
This should be described a bit more generically.  Apparently any invalid transaction, followed by a valid transaction, generates this error.  For instance I just tripped it again by trying a -0 amount transfer, which failed properly.  My next transfer attempt then fails with a nonce error.

**Comment by markmhendrickson** [comment]
@dantrevino Is this still an issue as far as you're aware?

**Comment by pseudozach** [comment]
I've been running into this issue for a while.
1- I've sent [this tx which failed](https://explorer.stacks.co/txid/0xf82f17c5813074968fe1a2572e941978b81adbdf95a331bccf56b25507906811?chain=testnet)
2- I've tried to trigger the same function call from sandbox and wallet tries to use nonce 589 and network rejects with "bad nonce" error.
When I check manually from cli, this account's latest nonce is 591.

**Comment by kyranjamie** [comment]
@markmhx No, I don't think so. Perhaps it's incrementing the nonce when a tx fails? @hstove could this be possible?

**Comment by psq** [comment]
I don't have any good way to reproduce this yet, but I've had a `Bad Nonce` error happen twice, and the only way to fix it is to reset the web wallet.

the first case I looked at, it was sending a nonce of 32 while the api for the account showed the current nonce was 33.  Second case, and I haven't reset, in case you'd like me to look at something before I do:

```
{"error":"transaction rejected","reason":"BadNonce","reason_data":{"actual":35,"expected":36,"is_origin":true,"principal":"ST2SVRCJJD90TER037VCSAFA781HQTCPFK9YRA6J5"},"txid":"20495962b1a893973917d635cc04aa1d0b237e1b38463c2924c3c9f8a3122eda"}
```

https://stacks-node-api.regtest.stacks.co/v2/accounts/ST2SVRCJJD90TER037VCSAFA781HQTCPFK9YRA6J5?proof=0 shows the current nonce as 36, however, the transaction is built with 35.

checking the mempool did not show any pending transaction for my address.

My main suspicion is that I queued more than one transaction prior to the bad nonce happening, so more than one transaction in a block, and I'm pretty sure both succeeded, so maybe the extension is keeping some data and does not account for multiple transactions having been sent and correctly executed in a single block?  (see above that resetting the wallet fixed the issue)

If I do find a way to reproduce, I'll probably create a new issue, but maybe the above will trigger something in someone's brain to help locate the issue?  no idea whether that's the same as the OP

**Comment by 314159265359879** [comment]
![image](https://user-images.githubusercontent.com/33360391/124919729-da28fc00-dff6-11eb-9f91-e974989629f8.png)
Mark asked me to make a note of my findings here. 

As opposed to psq I do find that sometimes this issue is resolved even without a reset of the wallet. I can recall three instances of that, taking a day maybe two. Only for ST2PBEZB3ZPHJE1XJHFQKGF6E08SV29K96WCRJA13 it has persisted since june 21st (I have not tried resetting the wallet btw). 

What is new to me with these nonce issues is that they do not get resolved once the mempool is cleared of transactions for that address. That has been my experience thus far. And I have only encountered this on regtest.

**Comment by markmhendrickson** [comment]
See this report from @duxin0817060114 via Arkadiko as well: https://github.com/arkadiko-dao/arkadiko/issues/103

**Comment by kyranjamie** [comment]
There's some pretty [heavy logic to calculate the nonce](https://github.com/blockstack/stacks-wallet-web/blob/688be6cf375fb7598c6a027603db64dda5f943ee/src/store/accounts/nonce.ts).

This is the [desktop wallet implementation](https://github.com/blockstack/stacks-wallet/blob/9a298300f2de914144e4317122adc4a36e813114/app/hooks/use-latest-nonce.ts#L13-L18) for comparison. @aulneau is all this needed? 🤔 I'm assuming the issue lies in there.

**Comment by psq** [comment]
still no smoking gun, as a follow up on my https://github.com/blockstack/stacks-wallet-web/issues/934#issuecomment-868408064, but I have been making sure I only send one transaction at a time (not queueing more than one), and wait for the transaction to be fully processed before sending an other one, and haven't had the bad nonce issue while doing this.

so queueing may be what's causing the failure (i.e. both process, but the web wallet only accounts for 1?)

**Comment by markmhendrickson** [comment]
@aulneau mind commenting with a link to the related API change that you mentioned may fix this once live? And a link to the related desktop wallet change, if you find that as well.

**Comment by markmhendrickson** [comment]
The required API changes are on the `develop` branch in that repository and can be used now to start with integration.

**Comment by Zk2u** [comment]
Seems like I'm getting a conflicting nonce because the 2nd account is using the same nonce as the original account

Eg, I'm trying to send transactions from Syvita's pool address which is my 8th account on the web wallet and it is using nonces starting from 64. 64 is the nonce on my primary address - the one that holds `asteria.btc`. This may be the issue.

**Comment by aulneau** [comment]
> Seems like I'm getting a conflicting nonce because the 2nd account is using the same nonce as the original account
> 
> Eg, I'm trying to send transactions from Syvita's pool address which is my 8th account on the web wallet and it is using nonces starting from 64. 64 is the nonce on my primary address - the one that holds `asteria.btc`. This may be the issue.

This makes a lot of sense, thank you! I think with this information I can probably create a reproduction and fix it.
