### ISSUE TITLE
logging in Username/account name doesn't display

### ISSUE THREAD

**Issue by timstackblock** [leather-io/extension#98]
When logging in Username/account name doesn't display, but a series of numbers are displayed in the usernames place.

Video of issue
https://screencast-o-matic.com/watch/cYnhogwDpc

<img width="544" alt="Screen Shot 2020-02-05 at 10 38 49 AM" src="https://user-images.githubusercontent.com/49165468/73856691-d8f10f80-4803-11ea-94e3-e41ab5fb622d.png">

**Comment by markmhendrickson** [comment]
@hstove Mind taking this one?

**Comment by hstove** [comment]
Ready for QA

This is actually an existing issue in the Browser, because you can't see which usernames an address owns until it's processed on-chain. However, we have a new mechanic for keeping internal (private) wallet settings in Gaia, and so we're using that to see if you have an existing username.

**Comment by dantrevino** [comment]
Can you explain how this "new mechanic for keeping internal wallet settings in Gaia" works @hstove ?

**Comment by markmhendrickson** [comment]
I've created a separate issue to track documentation for that mechanic here: https://github.com/blockstack/ux/issues/317
