### ISSUE TITLE
Design all transaction types and states

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#991]
![image](https://user-images.githubusercontent.com/25477905/108501389-802ad280-72b1-11eb-8193-c7d0922a8f68.png)

We have a place on the web wallet homepage where we show the latest transaction. The designs don't include all types and states. They should include the following:

Types

- [x] STX transfer
- [x] Token transfer (NFT or FT)
- [x] Protocol-level smart contracts like Stacking (and name registrations?)
- [x] Contract call
- [x] Contract deploy

States

- [x] Completed
- [x] Pending
- [x] Failed

A transaction should include the following information:

- [x] Which token (if applicable)
- [x] The amount (if FT or STX)
- [x] The time/date
- [x] Icon (if applicable)

**Comment by jasperjansz** [comment]
@aulneau @hstove for review:

Here's the matrix of transaction types: https://www.figma.com/file/8CaxP6TRWskoTO9cmlvX9M/%F0%9F%96%A5-Wallet-web?node-id=1580%3A398.

You can also take this one and toggle the type/state in the right-hand panel: https://www.figma.com/file/8CaxP6TRWskoTO9cmlvX9M/%F0%9F%96%A5-Wallet-web?node-id=1593%3A1.

You can see the activity feed in context here: https://www.figma.com/file/8CaxP6TRWskoTO9cmlvX9M/%F0%9F%96%A5-Wallet-web?node-id=1585%3A29579.

There's also the details screen. You get there by clicking an item in your activity feed: https://www.figma.com/file/8CaxP6TRWskoTO9cmlvX9M/%F0%9F%96%A5-Wallet-web?node-id=1585%3A28671.

Please review and let me know if there's any type, status, or anything else I've missed — also general feedback welcome of course!

**Comment by hstove** [comment]
Thanks Jasper, these are wonderful and really exciting. No comments on the detail view - its perfect.

- Are the contract deploys not done yet? They're showing as blank for me.
- For the generic gradient avatar, what is the source of the letter? This is mainly something that would be nice for us to have written down. For example, it could be:
  - first char of ticker (if available)
  - first char of contract name

Re: contract calls, I would appreciate some clarification:

- Where does "Set bid" come from? Is it a function name, "title-ized" (i.e. `set-bid` -> "Set bid")
- Where does the Avatar come from?
- Where does "Zora" come from? Is it the contract name, title-ized?

I think we'll be able to get most of this "best case" metadata via the newer traits. I think my main ask would be to have some fallbacks for contract calls that aren't FT/NFT transfers, and other "edge cases".

- What if the contract name is very long?
- What if it's an NFT/FT transfer, but not for a token that follows the trait (so there is no ticker, icon, name)
- What if a contract call executes multiple asset transfers?

Some examples of "generic" or non-standard tx's:

- [FT token transfer, but not a trait](https://explorer.stacks.co/txid/0x0920b6e26c8ce57fdde871738dfcb95526ec2d313c5435e28c8618576e50963b?chain=mainnet)
- [Contract call minting many NFTs](https://explorer.stacks.co/txid/0x1bab6ca7cf2c588de7063971058f02ecc7e27ff4951e29dc58d75a57acd10c9b?chain=mainnet)
- [`send-many` contract call](https://explorer.stacks.co/txid/0xe5b81a19bb10cabe1326dc0041775366fa0e791e2c62d6e0d1b2449dd48a9d2f?chain=mainnet) - This is going to be a common one, as it happens for all binance withdraws. This will show up in the user's feed, since there is one (or more) "inbound" asset transfer. Can we design something that is smart around displaying the asset transfer related to the current user?
- [`stack-stx`](https://explorer.stacks.co/txid/0xda3b981df7b547243f29aed879cce286a5e6a9efe78af9955e7c92b0c6034e58?chain=mainnet) - is this basically following the "Set bid" pattern? So title would be "Stack stx" (following your capitalization), name would be "Pox"

I love this work. I know that we can definitely build helpful specialized tx items (like we have for the desktop wallet), but it would be great to start with super generic fallbacks, with smart "upgrade" components for true FT/NFT contracts, pox, send-many, etc.

While I'm brain dumping, what if we designed something that displayed the exchange name, instead of the STX address? The STX addresses for all exchanges are known and unchanging.

**Comment by aulneau** [comment]
I don't have much feedback as I think I've covered a lot of that last week during our syncs -- but I would echo what hank is pointing at -> we need to design these screens with real information. While it's great and important to design these with what we hope we will have, many of the elements here reflect what things will be like in the future, and ultimately inform how we define these standards. I'd love to see a version of these with worst case (realistic to what it would be today) scenario data. Very long names, no formatting of function names to sentences. No images what-so-ever. What if there are 40 events? 200?

Small nit, I think + and - signs might be better for received and sent. <- and -> are still subjective depending on where the user thinks of themselves :) what if the user is use to right-to-left in place of left-to-right?

I am a huge fan of the new activity / balances switch. 

All in all I am so stoked about this work :) excited to build it!

**Comment by jasperjansz** [comment]
Made some more updates:

Check all transaction types here: https://www.figma.com/file/8CaxP6TRWskoTO9cmlvX9M/%F0%9F%96%A5-Wallet-web?node-id=1580%3A398

I've also got all types of tx detail screens here: https://www.figma.com/file/8CaxP6TRWskoTO9cmlvX9M/%F0%9F%96%A5-Wallet-web?node-id=1650%3A34720

I've also started this 'playground' page where I'll be putting screens and components for you to toggle between states without worrying about breaking the designs. The homepage is on there and you play with the transaction and balance components to see them in action
